version: 0.1

phases:
  install:
    runtime-versions:
      java: openjdk11
 build:
   commands:
     - echo Entering build phase...
     - echo Build started on date
     - mvn install
 post_build:
   commands:
     - echo Entering post_build phase...
     - echo Build completed on date

artifacts:
  files:
    - webgoat-server/target/webgoat-server-8.0-SNAPSHOT.jar
  discard-paths: yes

